import { useState, useEffect } from 'react';
import { Sidebar } from './Dashboard/layout/Sidebar';
import { Header } from './Dashboard/layout/Header';
import { BottomNav } from './Dashboard/layout/BottomNav';
import { useNavigate } from 'react-router-dom';

interface SignalPackage {
  id: string;
  name: string;
  price: number;
  strength: number;
}

const HOW_IT_WORKS = [
  { q: 'What are Signals?', a: 'Signals are professional trading indicators generated by our AI algorithms and expert traders. They provide buy/sell recommendations for various crypto assets.' },
  { q: 'How do I use Signals?', a: 'Purchase a signal package that fits your trading style. Once active, you\'ll receive real-time trading alerts and recommendations via your dashboard.' },
  { q: 'How long are Signals valid?', a: 'Signal packages remain active as long as your subscription is valid. Each package is a one-time purchase that gives you access to the signal for its duration.' },
  { q: 'What does Signal Strength mean?', a: 'Signal strength indicates the confidence level of our trading algorithm. A 10% strength means high-conviction trades with a strong historical win rate.' },
];

export const Signals = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<'signals' | 'history' | 'howItWorks'>('signals');
  const [packages, setPackages] = useState<SignalPackage[]>([]);
  const [balance, setBalance] = useState(0);
  const [activeSignal, setActiveSignal] = useState<string | null>(null);
  const [history, setHistory] = useState<any[]>([]);
  const [amounts, setAmounts] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [purchasing, setPurchasing] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const token = localStorage.getItem('token');

  useEffect(() => {
    fetchPackages();
    fetchMyData();
  }, []);

  const fetchPackages = async () => {
    try {
      const res = await fetch('/api/signals/packages', {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.packages) {
        setPackages(data.packages);
        const initAmounts: Record<string, string> = {};
        data.packages.forEach((p: SignalPackage) => {
          initAmounts[p.id] = String(p.price);
        });
        setAmounts(initAmounts);
      }
    } catch {}
    setLoading(false);
  };

  const fetchMyData = async () => {
    try {
      const res = await fetch('/api/signals/my', {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.balance !== undefined) setBalance(data.balance);
      if (data.activeSignal) setActiveSignal(data.activeSignal);
      if (data.purchases) setHistory(data.purchases);
    } catch {}
  };

  const handlePurchase = async (packageId: string) => {
    setError(null);
    setSuccess(null);
    setPurchasing(packageId);
    try {
      const res = await fetch('/api/signals/purchase', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ packageId, amount: amounts[packageId] }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || 'Purchase failed');
      } else {
        setSuccess('Signal package purchased successfully!');
        fetchMyData();
      }
    } catch {
      setError('Network error. Please try again.');
    }
    setPurchasing(null);
  };

  const strengthBars = (strength: number) => {
    const bars = Math.round(strength / 10);
    return (
      <div className="flex gap-0.5">
        {Array.from({ length: 10 }).map((_, i) => (
          <div key={i} className={`w-2.5 h-3 rounded-sm ${i < bars ? 'bg-red-500' : 'bg-[#2a2a2a]'}`} />
        ))}
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white font-inter overflow-x-hidden">
      <Sidebar />
      <div className="flex-1 md:ml-[260px] flex flex-col min-h-screen">
        <Header />

        <main className="flex-1 p-4 md:p-8 max-w-7xl mx-auto w-full pb-32 md:pb-8">
          {/* Top bar */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
            <div className="flex flex-col gap-1">
              <div className="flex items-center gap-2 text-gray-400 text-sm">
                <span>Signal Balance</span>
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" /></svg>
              </div>
              <div className="text-[32px] font-bold">${balance.toLocaleString()}</div>
              <button
                onClick={() => navigate('/deposit')}
                className="self-start flex items-center gap-2 px-4 py-2 bg-[#141414] border border-[#2a2a2a] text-white text-sm font-medium rounded-lg hover:bg-[#1a1a1a] transition-colors mt-1"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" /></svg>
                Deposit
              </button>
            </div>
            <div>
              <div className="text-sm text-gray-400 mb-2">Signal strength</div>
              <div className="flex gap-0.5 flex-wrap">
                {Array.from({ length: 20 }).map((_, i) => (
                  <div key={i} className={`h-4 w-3 rounded-sm ${i < 2 ? 'bg-red-600' : 'bg-[#2a2a2a]'}`} />
                ))}
              </div>
              <div className="text-xs text-gray-600 mt-1 text-right">0%</div>
              <div className="text-sm text-gray-500 mt-2">
                Your active signal is: <span className="text-white">{activeSignal || '-'}</span>
              </div>
            </div>
          </div>

          {/* Tabs */}
          <div className="flex gap-6 border-b border-[#222] mb-8">
            {(['signals', 'history', 'howItWorks'] as const).map(tab => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`pb-3 text-sm font-bold transition-colors border-b-2 -mb-px ${
                  activeTab === tab ? 'text-white border-[#ff6a00]' : 'text-gray-500 border-transparent hover:text-gray-300'
                }`}
              >
                {tab === 'howItWorks' ? 'How it works' : tab === 'history' ? 'Your history' : 'Signals'}
              </button>
            ))}
          </div>

          {error && <div className="mb-6 p-4 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400 text-sm">{error}</div>}
          {success && <div className="mb-6 p-4 bg-green-500/10 border border-green-500/30 rounded-xl text-green-400 text-sm">{success}</div>}

          {/* Signals Tab */}
          {activeTab === 'signals' && (
            <div className="animate-in fade-in duration-300">
              <h2 className="text-base font-bold text-white mb-6">Signals</h2>
              {loading ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {[1,2,3,4,5,6].map(i => (
                    <div key={i} className="bg-[#141414] border border-[#222] rounded-xl p-5 animate-pulse h-52" />
                  ))}
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {packages.map(pkg => (
                    <div key={pkg.id} className="bg-[#141414] border border-[#222] rounded-xl p-5 flex flex-col gap-4 hover:border-[#333] transition-colors">
                      <h3 className="text-[#ff6a00] font-bold text-sm">{pkg.name}</h3>
                      <div className="space-y-2.5 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-500">Signal price</span>
                          <span className="text-white font-medium">${Number(pkg.price).toLocaleString()}.00</span>
                        </div>
                        <div className="flex justify-between items-center border-t border-[#1e1e1e] pt-2.5">
                          <span className="text-gray-500">Signal strength</span>
                          <div className="flex items-center gap-2">
                            <span className="text-red-500 font-bold text-xs">{pkg.strength}%</span>
                            {strengthBars(pkg.strength)}
                          </div>
                        </div>
                      </div>
                      <div>
                        <label className="text-xs text-gray-500 block mb-1">Amount</label>
                        <div className="flex items-center bg-[#0d0d0d] border border-[#2a2a2a] rounded-lg overflow-hidden">
                          <input
                            type="number"
                            value={amounts[pkg.id] || ''}
                            onChange={e => setAmounts(prev => ({ ...prev, [pkg.id]: e.target.value }))}
                            className="flex-1 bg-transparent px-3 py-2 text-white text-sm outline-none"
                          />
                          <span className="px-3 text-gray-500 text-xs border-l border-[#2a2a2a]">USD</span>
                        </div>
                        <div className="flex justify-between text-xs mt-1">
                          <span className="text-gray-600">Current balance</span>
                          <span className="text-gray-600">${balance.toFixed(2)}</span>
                        </div>
                      </div>
                      <button
                        onClick={() => handlePurchase(pkg.id)}
                        disabled={purchasing === pkg.id}
                        className="w-full py-2.5 rounded-lg text-sm font-bold transition-colors bg-[#2a2a2a] hover:bg-[#ff6a00] text-gray-300 hover:text-white disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        {purchasing === pkg.id ? 'Processing...' : 'Purchase'}
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* History Tab */}
          {activeTab === 'history' && (
            <div className="animate-in fade-in duration-300">
              <div className="bg-[#141414] border border-[#222] rounded-xl overflow-x-auto">
                <table className="w-full text-left min-w-[500px]">
                  <thead>
                    <tr className="border-b border-[#222]">
                      <th className="p-4 text-xs font-medium text-gray-500">Signal</th>
                      <th className="p-4 text-xs font-medium text-gray-500">Amount</th>
                      <th className="p-4 text-xs font-medium text-gray-500">Status</th>
                      <th className="p-4 text-xs font-medium text-gray-500">Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    {history.length === 0 ? (
                      <tr><td colSpan={4} className="p-8 text-center text-gray-500 text-sm">No signal purchases yet</td></tr>
                    ) : history.map((p: any) => (
                      <tr key={p.id} className="border-t border-[#1a1a1a] hover:bg-[#1a1a1a] transition-colors">
                        <td className="p-4 text-sm text-white">{p.package?.name}</td>
                        <td className="p-4 text-sm text-white">${Number(p.amount).toLocaleString()}</td>
                        <td className="p-4 text-sm">
                          <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${p.status === 'ACTIVE' ? 'bg-green-500/20 text-green-400' : 'bg-gray-500/20 text-gray-400'}`}>{p.status}</span>
                        </td>
                        <td className="p-4 text-sm text-gray-400">{new Date(p.createdAt).toLocaleDateString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* How it works Tab */}
          {activeTab === 'howItWorks' && (
            <div className="animate-in fade-in duration-300 max-w-3xl">
              <h2 className="text-xl font-bold text-white mb-6">How it works</h2>
              <div className="space-y-4">
                {HOW_IT_WORKS.map((item, index) => (
                  <div key={index} className="bg-[#141414] border border-[#222] rounded-xl overflow-hidden">
                    <button
                      onClick={() => setOpenFaq(openFaq === index ? null : index)}
                      className="w-full p-4 flex items-center justify-between hover:bg-[#1a1a1a] transition-colors text-left"
                    >
                      <div className="flex items-center gap-3">
                        <div className="w-6 h-6 bg-[#2a2a2a] rounded flex items-center justify-center text-xs font-bold text-white shrink-0">{index + 1}</div>
                        <span className="font-bold text-sm text-white">{item.q}</span>
                      </div>
                      <svg className={`w-5 h-5 text-gray-500 transition-transform duration-300 ${openFaq === index ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" /></svg>
                    </button>
                    <div className={`transition-all duration-300 ${openFaq === index ? 'max-h-40 opacity-100' : 'max-h-0 opacity-0'} overflow-hidden`}>
                      <div className="p-4 pt-0 text-sm text-gray-400 leading-relaxed ml-9 border-t border-[#222] mt-2">{item.a}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </main>
      </div>
      <BottomNav />
    </div>
  );
};
